FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
RUN python -m spacy download en
ADD . /code/


COPY run.sh /code/run.sh

WORKDIR /code
CMD ["/code/run.sh"]
