# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 16:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPartOfBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.TextField()),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Character')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.TextField()),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('sentence_number', models.IntegerField()),
                ('word_number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sentence_number', models.IntegerField()),
                ('word_number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
